{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1554.0 (23.12)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Territory Lookup\",\"Product Lookup\",\"Product Category Lookup\",\"Product Subcategory Lookup\",\"Customer Lookup DQ\",\"Customer Lookup\",\"Calendar\",\"Internet Sales\",\"Reseller Sales\",\"CurrentDatabase\",\"CurrentServer\",\"SalesMinimumDate\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "CurrentDatabase",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"AdventureWorksDW2019\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "d3368362-9e0a-417d-ab39-f75e77578a5b",
        "queryGroup": "Parameters"
      },
      {
        "name": "CurrentServer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\".\" meta [IsParameterQuery=true, List={\".\", \"prod.azure.com\"}, DefaultValue=\".\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "e171319e-4234-4cce-bfca-310e1286fe92",
        "queryGroup": "Parameters"
      },
      {
        "name": "SalesMinimumDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"2013-11-10\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "fc440b33-5892-4e08-9abd-b58e7d63b7cd",
        "queryGroup": "Parameters"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Parameters"
      }
    ],
    "relationships": [
      {
        "name": "9c97e787-2f56-4189-9a80-b9670f16f6e1",
        "fromColumn": "StartDate",
        "fromTable": "Product Lookup",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_8b4d6d0e-bc68-481e-9282-8a182ecf2e4e"
      },
      {
        "name": "e592823b-cb03-4eae-b65b-afb972e0a8c9",
        "fromColumn": "EndDate",
        "fromTable": "Product Lookup",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_42528443-5a4c-4a07-b0b4-7c7d97e55e0c"
      },
      {
        "name": "4a1502c3-bc15-498d-8955-ba41c3c58fdd",
        "fromColumn": "BirthDate",
        "fromTable": "Customer Lookup",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3acdb546-8f22-4f5e-9346-fb0821380efb"
      },
      {
        "name": "cfca05d3-2d55-4d3f-9e6a-1048bda86bc7",
        "fromColumn": "Date",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_54a07bb5-47eb-4eb7-a5d9-f864f5739ef7"
      },
      {
        "name": "ca376516-eef8-417f-b315-113b147f830a",
        "fromColumn": "Start of Year",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2df8943f-f7d7-4ecb-ba1f-115dada4382b"
      },
      {
        "name": "4974fbdb-457e-4a13-aed8-19cf5835e3cc",
        "fromColumn": "Start of Quarter",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c6f5922e-0704-441e-86d9-3aea5517a74c"
      },
      {
        "name": "06b181e4-ffdc-498a-82de-ea2619f91c8c",
        "fromColumn": "BirthDate",
        "fromTable": "Customer Lookup DQ",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b8db72a3-b675-44d9-9220-a6793d123884"
      },
      {
        "name": "781f44d5-5ccb-42e3-aefd-429837ec2266",
        "fromColumn": "OrderDate",
        "fromTable": "Internet Sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d4a38875-966c-4add-b851-15addb1ccf37"
      },
      {
        "name": "4750832d-7172-4883-8254-4bc74e24cb11",
        "fromColumn": "DueDate",
        "fromTable": "Internet Sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_1080db56-9b62-43c7-aab3-369e2bcfd477"
      },
      {
        "name": "7c6950ca-b538-4505-99bc-8952a4067ea3",
        "fromColumn": "ShipDate",
        "fromTable": "Internet Sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e2a3474b-1858-47bf-91f7-d73bed853a8c"
      },
      {
        "name": "c70bdd04-796e-493f-aa3e-fcc8cc052779",
        "fromColumn": "OrderDate",
        "fromTable": "Reseller Sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_8926865d-b7b2-48e8-953a-652fd20ab5d2"
      },
      {
        "name": "7c569d3e-d609-43e6-9812-2adc36b86b84",
        "fromColumn": "DueDate",
        "fromTable": "Reseller Sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_433f3959-dd6b-49bf-b184-1d41229b4926"
      },
      {
        "name": "a3f786ac-2136-4576-8f95-1f7f21c16507",
        "fromColumn": "ShipDate",
        "fromTable": "Reseller Sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a0ff8239-4169-4262-8605-6db69c81c6c0"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Product Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "186f1686-e1ba-4c62-91e5-a6c969957664",
            "sourceColumn": "ProductKey",
            "summarizeBy": "count"
          },
          {
            "name": "ProductAlternateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1bb3c26-69e4-460f-9349-07a7cd63485e",
            "sourceColumn": "ProductAlternateKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSubcategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "96ee21c5-c126-46ba-9c5e-da6e5b01cfae",
            "sourceColumn": "ProductSubcategoryKey",
            "summarizeBy": "count"
          },
          {
            "name": "WeightUnitMeasureCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "282c45a8-e439-495f-bdc0-1c8e57abca61",
            "sourceColumn": "WeightUnitMeasureCode",
            "summarizeBy": "none"
          },
          {
            "name": "SizeUnitMeasureCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9de19186-0bba-4338-8ac8-f02a70072374",
            "sourceColumn": "SizeUnitMeasureCode",
            "summarizeBy": "none"
          },
          {
            "name": "EnglishProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c04867cb-0aaf-4357-81fd-de35b02dfb84",
            "sourceColumn": "EnglishProductName",
            "summarizeBy": "none"
          },
          {
            "name": "StandardCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bccfd3f5-3504-48a6-a149-e2d7c728e346",
            "sourceColumn": "StandardCost",
            "summarizeBy": "sum"
          },
          {
            "name": "FinishedGoodsFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "13bc9201-60c5-48ae-a760-c9fbc873faf1",
            "sourceColumn": "FinishedGoodsFlag",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8007225a-e547-4aff-93b7-76916f2d40fb",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "SafetyStockLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e31418a1-1651-4a82-b7f0-c22cf2c60fdf",
            "sourceColumn": "SafetyStockLevel",
            "summarizeBy": "sum"
          },
          {
            "name": "ReorderPoint",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d5284fd2-01b3-4e37-9c5d-7bcf9a95414c",
            "sourceColumn": "ReorderPoint",
            "summarizeBy": "sum"
          },
          {
            "name": "ListPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "af8be974-3a36-4953-a2b3-8f5c1f4790aa",
            "sourceColumn": "ListPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "Size",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "daf9df69-6c88-40b0-8673-c960862ae2d8",
            "sourceColumn": "Size",
            "summarizeBy": "none"
          },
          {
            "name": "SizeRange",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c938784a-4887-4917-9b65-924258b74798",
            "sourceColumn": "SizeRange",
            "summarizeBy": "none"
          },
          {
            "name": "Weight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "183f57af-7d25-4a08-81d2-b3233b72d939",
            "sourceColumn": "Weight",
            "summarizeBy": "sum"
          },
          {
            "name": "DaysToManufacture",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c7c236ba-c4f9-4770-8ab8-7560d7baa3e4",
            "sourceColumn": "DaysToManufacture",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductLine",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "37373eed-2e89-46a8-8dcd-24ba80b1f0aa",
            "sourceColumn": "ProductLine",
            "summarizeBy": "none"
          },
          {
            "name": "DealerPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "f796d627-c3f4-4e7b-a52d-ea344010961d",
            "sourceColumn": "DealerPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "Class",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8838e61-c0a6-4e81-b8cb-c0e8bd001941",
            "sourceColumn": "Class",
            "summarizeBy": "none"
          },
          {
            "name": "Style",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33da15f9-7067-456a-a591-fa91ccbf563f",
            "sourceColumn": "Style",
            "summarizeBy": "none"
          },
          {
            "name": "ModelName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "719abc57-8dd5-41a0-8599-bb8c19f9fa83",
            "sourceColumn": "ModelName",
            "summarizeBy": "none"
          },
          {
            "name": "EnglishDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9088e8dd-9dc3-448e-871c-7562b926e39b",
            "sourceColumn": "EnglishDescription",
            "summarizeBy": "none"
          },
          {
            "name": "StartDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "834bc9f9-a1e9-49ac-8fd7-2c830321de62",
            "sourceColumn": "StartDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_8b4d6d0e-bc68-481e-9282-8a182ecf2e4e"
                },
                "isDefault": true,
                "relationship": "9c97e787-2f56-4189-9a80-b9670f16f6e1"
              }
            ]
          },
          {
            "name": "EndDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "71247f4d-d6ac-4106-a24b-e669ba5fb94c",
            "sourceColumn": "EndDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_42528443-5a4c-4a07-b0b4-7c7d97e55e0c"
                },
                "isDefault": true,
                "relationship": "e592823b-cb03-4eae-b65b-afb972e0a8c9"
              }
            ]
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "374daf24-92af-4fe5-a93e-6a373886d7a7",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "SKU Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90c65f31-f38e-4fb1-93f1-8eade76be163",
            "sourceColumn": "SKU Type",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8b3e7ffb-fbaa-450a-87f6-835000331cc1",
        "partitions": [
          {
            "name": "Product Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(CurrentServer, CurrentDatabase, [Query=\"SELECT [ProductKey]#(lf)      ,[ProductAlternateKey]#(lf)      ,[ProductSubcategoryKey]#(lf)      ,[WeightUnitMeasureCode]#(lf)      ,[SizeUnitMeasureCode]#(lf)      ,[EnglishProductName]#(lf)      ,[StandardCost]#(lf)      ,[FinishedGoodsFlag]#(lf)      ,[Color]#(lf)      ,[SafetyStockLevel]#(lf)      ,[ReorderPoint]#(lf)      ,[ListPrice]#(lf)      ,[Size]#(lf)      ,[SizeRange]#(lf)      ,[Weight]#(lf)      ,[DaysToManufacture]#(lf)      ,[ProductLine]#(lf)      ,[DealerPrice]#(lf)      ,[Class]#(lf)      ,[Style]#(lf)      ,[ModelName]#(lf)      ,[LargePhoto]#(lf)      ,[EnglishDescription]#(lf)      ,[StartDate]#(lf)      ,[EndDate]#(lf)      ,[Status]#(lf)  FROM [dbo].[DimProduct]\", CreateNavigationProperties=false]),",
                "    #\"Change to Currency\" = Table.TransformColumnTypes(Source,{{\"DealerPrice\", Currency.Type}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Change to Currency\", \"SKU Type\", each ",
                "Text.BeforeDelimiter([ProductAlternateKey],\"-\",1)",
                "    ),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Added Custom\", each true),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Filtered Rows\",null,\"N/A\",Replacer.ReplaceValue,{\"Style\"})",
                "in",
                "    #\"Replaced Value\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_18e443f7-20a5-47af-9af7-99b1a1710446",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "75c32deb-98aa-4f24-99b9-02e51fe5ba55",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3124bed7-95bd-47cb-999c-58fcda0bab0d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "91704f19-319b-4f1e-9d8c-39ad04f63622",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "bd324b19-ac2f-457a-b519-72e622d86cd8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8890d8f6-449f-4473-8c83-52cd09a2232a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "b303b0bc-7cad-41c5-9fee-3901552234a3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "788f1c91-fdb3-4d88-810d-2a5295571114",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "304e7536-f769-4ddb-acd0-675b0520c95c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "92aad8a1-99fd-4223-92b3-648ba7c77a5f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6bc1dd00-5158-4929-b0ce-a023e571fcc3",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b3672a2e-279c-441b-b3ea-fbdbf53b2b04",
                "ordinal": 3
              }
            ],
            "lineageTag": "901b7c47-8f9a-4a33-93c9-f2f461029df1"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "619da7f9-58f5-44b0-ac79-a674e7a6e9f0",
        "partitions": [
          {
            "name": "DateTableTemplate_18e443f7-20a5-47af-9af7-99b1a1710446",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_8b4d6d0e-bc68-481e-9282-8a182ecf2e4e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9eb8a4ce-0d67-455c-af6a-23330e1159ac",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c25f6e26-f5f9-41c3-a12a-250665717219",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e0ac8285-a0dc-4d3e-8523-a19d13ec0b9f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8ed6874e-7bfd-4339-a6e2-99455740c2ad",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f8ffb003-4101-4d65-b337-16523d0dc436",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "892f668a-ddfc-489a-99c8-3e8522697ea7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d52395e7-c0a5-4f8d-a76f-c17d7267ab43",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "336af349-2ed1-45ee-8b7c-b20f5e1415ec",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "aada1db7-a14b-453e-b652-168e5544c6a5",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "461a7f34-cdf2-4344-9190-7527d0c341a5",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1704d0af-e220-436d-b2bc-f528c9ee581d",
                "ordinal": 3
              }
            ],
            "lineageTag": "53e435d2-1d2a-4c45-954a-282f4a97ff9f"
          }
        ],
        "isHidden": true,
        "lineageTag": "841b3d4b-6e62-4fb6-a410-68d56c6f6c67",
        "partitions": [
          {
            "name": "LocalDateTable_8b4d6d0e-bc68-481e-9282-8a182ecf2e4e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Product Lookup'[StartDate])), 1, 1), Date(Year(MAX('Product Lookup'[StartDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_42528443-5a4c-4a07-b0b4-7c7d97e55e0c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "22f9106b-b5b3-496e-8863-b3413b6bbf00",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "20bc374d-5f07-4977-9701-f97d9cfe4d18",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d8967f81-a3ae-4033-abc6-5f9464d75ae2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6a28ff8e-8f92-45bf-a37c-1e7af717f677",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8a5707cb-6ef9-4020-9d8b-d8186e94a677",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "aa54e3fe-6c94-4830-b7a4-1fcf468c30fb",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "adfbd3fa-a95b-452c-a5f8-525c9f7fbc64",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7bd6ea64-91df-4262-bf37-b1ddbff270f3",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a04c5851-cff9-4678-b295-f5762b989575",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "99cf5831-0bea-4f68-bdef-11897bf2a524",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "9a020a59-d3ab-4412-b825-63fb13235327",
                "ordinal": 3
              }
            ],
            "lineageTag": "5a69d75d-4389-4a9f-9db4-29fa731e574d"
          }
        ],
        "isHidden": true,
        "lineageTag": "73767954-7be7-40a5-963e-5ed1a96caee5",
        "partitions": [
          {
            "name": "LocalDateTable_42528443-5a4c-4a07-b0b4-7c7d97e55e0c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Product Lookup'[EndDate])), 1, 1), Date(Year(MAX('Product Lookup'[EndDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Territory Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SalesTerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "07b2f2d7-e82b-4d3d-b1a5-8ba26a31487c",
            "sourceColumn": "SalesTerritoryKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "SalesTerritoryAlternateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "636194c4-ee1a-45e8-99a7-a0b584681528",
            "sourceColumn": "SalesTerritoryAlternateKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "SalesTerritoryRegion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "ae48f413-02a5-471b-b3a6-2acfbfe427f9",
            "sourceColumn": "SalesTerritoryRegion",
            "sourceProviderType": "nvarchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryCountry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "44cc98c1-b3c6-4159-b91d-f4fd7665d257",
            "sourceColumn": "SalesTerritoryCountry",
            "sourceProviderType": "nvarchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "654cd5fe-587c-45db-ae0b-426897d9a06b",
            "sourceColumn": "SalesTerritoryGroup",
            "sourceProviderType": "nvarchar(50)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bfdfb20c-bee9-42e6-9df3-9d26346163ad",
        "partitions": [
          {
            "name": "Territory Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(CurrentServer, CurrentDatabase, [Query=\"SELECT [SalesTerritoryKey]#(lf)      ,[SalesTerritoryAlternateKey]#(lf)      ,[SalesTerritoryRegion]#(lf)      ,[SalesTerritoryCountry]#(lf)      ,[SalesTerritoryGroup]#(lf)      ,[SalesTerritoryImage]#(lf)  FROM [dbo].[DimSalesTerritory]\", CreateNavigationProperties=false])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product Category Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductCategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "42fc53e2-3126-4b95-a482-5d22e39bf768",
            "sourceColumn": "ProductCategoryKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "CategoryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "83d34ccc-58ea-4eda-a670-beaa453d80db",
            "sourceColumn": "CategoryName",
            "sourceProviderType": "nvarchar(50)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ea63aa7e-c557-4d25-b46b-b5752aa12a52",
        "partitions": [
          {
            "name": "Product Category Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(CurrentServer, CurrentDatabase, [Query=\"SELECT [ProductCategoryKey]#(lf)      ,[EnglishProductCategoryName] as [CategoryName]#(lf)  FROM [dbo].[DimProductCategory]\", CreateNavigationProperties=false])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product Subcategory Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductSubcategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "d6742f97-7212-477e-a88d-65854e461541",
            "sourceColumn": "ProductSubcategoryKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "SubcategoryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "7de1a814-4bc7-4f6b-bdee-f7869cee7e4b",
            "sourceColumn": "SubcategoryName",
            "sourceProviderType": "nvarchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6f5b81aa-8962-416a-a515-a34e4a003764",
            "sourceColumn": "ProductCategoryKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "386fe30e-6c1b-499b-9214-976de88c305c",
        "partitions": [
          {
            "name": "Product Subcategory Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(CurrentServer, CurrentDatabase, [Query=\"SELECT [ProductSubcategoryKey]#(lf)      ,[EnglishProductSubcategoryName] as [SubcategoryName]#(lf)      ,[ProductCategoryKey]#(lf)  FROM [dbo].[DimProductSubcategory]\", CreateNavigationProperties=false])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer Lookup DQ",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "dbb818c6-fb40-48cb-a20a-3130c97b44fc",
            "sourceColumn": "CustomerKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "GeographyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "545180f4-1f99-4829-a11c-412608c96987",
            "sourceColumn": "GeographyKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "CustomerAlternateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "a98620fd-ffe6-48d4-9f43-db7e89cb82e2",
            "sourceColumn": "CustomerAlternateKey",
            "sourceProviderType": "nvarchar(15)",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b66886e-4df2-4aae-8dc3-12623ae1173b",
            "sourceColumn": "Title",
            "sourceProviderType": "nvarchar(8)",
            "summarizeBy": "none"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "261dd9a9-bbe2-4338-ac8a-58428ef1184b",
            "sourceColumn": "FirstName",
            "sourceProviderType": "nvarchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70697492-d808-4324-9cb5-f5a71ed1b003",
            "sourceColumn": "LastName",
            "sourceProviderType": "nvarchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "BirthDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "b38d23a1-2a38-48a8-814e-87339f119c47",
            "sourceColumn": "BirthDate",
            "sourceProviderType": "date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_b8db72a3-b675-44d9-9220-a6793d123884"
                },
                "isDefault": true,
                "relationship": "06b181e4-ffdc-498a-82de-ea2619f91c8c"
              }
            ]
          },
          {
            "name": "MaritalStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9402d10-55e0-4c42-9b15-55b278355ccf",
            "sourceColumn": "MaritalStatus",
            "sourceProviderType": "nchar",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5fc50e8-bfa7-409d-8d50-556058d466cc",
            "sourceColumn": "Gender",
            "sourceProviderType": "nvarchar(1)",
            "summarizeBy": "none"
          },
          {
            "name": "EmailAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a57693c2-c974-4ead-9520-5b88672ebca0",
            "sourceColumn": "EmailAddress",
            "sourceProviderType": "nvarchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "YearlyIncome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0076b2ce-69c6-4f33-a875-8252964c0662",
            "sourceColumn": "YearlyIncome",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalChildren",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5ceb37f5-6b16-49d3-9b28-8cee75fc6860",
            "sourceColumn": "TotalChildren",
            "sourceProviderType": "tinyint",
            "summarizeBy": "sum"
          },
          {
            "name": "EnglishEducation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afd7dc8b-5764-4903-9186-c45fd6a6eef3",
            "sourceColumn": "EnglishEducation",
            "sourceProviderType": "nvarchar(40)",
            "summarizeBy": "none"
          },
          {
            "name": "EnglishOccupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b261e464-f6f0-4aac-afb3-dece7cdd67a3",
            "sourceColumn": "EnglishOccupation",
            "sourceProviderType": "nvarchar(100)",
            "summarizeBy": "none"
          },
          {
            "name": "HouseOwnerFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55e3061d-3e8f-4bc0-9d8e-ab8c4e6df1f4",
            "sourceColumn": "HouseOwnerFlag",
            "sourceProviderType": "nchar",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "329a9d01-94a4-436a-ac9a-5a8bf2537678",
        "partitions": [
          {
            "name": "Customer Lookup DQ",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(CurrentServer, CurrentDatabase, [Query=\"SELECT [CustomerKey]#(lf)      ,[GeographyKey]#(lf)      ,[CustomerAlternateKey]#(lf)      ,[Title]#(lf)      ,[FirstName]#(lf)      ,[LastName]#(lf)      ,[BirthDate]#(lf)      ,[MaritalStatus]#(lf)      ,[Gender]#(lf)      ,[EmailAddress]#(lf)      ,[YearlyIncome]#(lf)      ,[TotalChildren]#(lf)      ,[EnglishEducation]#(lf)      ,[EnglishOccupation]#(lf)      ,[HouseOwnerFlag]#(lf)  FROM [dbo].[DimCustomer]\", CreateNavigationProperties=false])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c5f36122-e0bb-46cf-b521-32a4ba86d05d",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "count"
          },
          {
            "name": "GeographyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b978efdb-8f95-4fa3-80a7-174ba7b2df96",
            "sourceColumn": "GeographyKey",
            "summarizeBy": "count"
          },
          {
            "name": "CustomerAlternateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83359f8c-6e22-49d3-9d2b-ee65d9414299",
            "sourceColumn": "CustomerAlternateKey",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "634af670-2a00-42f6-a80f-9a641269a900",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0372fbe5-eafc-4354-97d4-ccf23f945648",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c8288d0-1474-4998-80be-130ce4887c84",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          },
          {
            "name": "BirthDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "1be609a1-03e8-44b2-b4d0-62bf0cfbf0a9",
            "sourceColumn": "BirthDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3acdb546-8f22-4f5e-9346-fb0821380efb"
                },
                "isDefault": true,
                "relationship": "4a1502c3-bc15-498d-8955-ba41c3c58fdd"
              }
            ]
          },
          {
            "name": "MaritalStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc575aec-588c-4c26-90fa-f85454c93bda",
            "sourceColumn": "MaritalStatus",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84cf886b-d0fe-412f-bf37-b5b4daf8b701",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "EmailAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4919a6b2-6e49-4989-a4e8-23a94ca2796a",
            "sourceColumn": "EmailAddress",
            "summarizeBy": "none"
          },
          {
            "name": "YearlyIncome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8271980c-828b-4b1f-bc02-100f43da646c",
            "sourceColumn": "YearlyIncome",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalChildren",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "76208505-b46e-4752-b686-ffb80d0fb00a",
            "sourceColumn": "TotalChildren",
            "summarizeBy": "sum"
          },
          {
            "name": "EnglishEducation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0328e5d-a68e-4282-8308-127318810b85",
            "sourceColumn": "EnglishEducation",
            "summarizeBy": "none"
          },
          {
            "name": "EnglishOccupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c16f2eca-7cfc-41db-8aec-0f59f2d6166f",
            "sourceColumn": "EnglishOccupation",
            "summarizeBy": "none"
          },
          {
            "name": "HouseOwnerFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81249cf3-4c3a-4f45-a1da-5f27a11c6a1e",
            "sourceColumn": "HouseOwnerFlag",
            "summarizeBy": "none"
          },
          {
            "name": "Domain",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a90d3680-ad37-4dfc-883e-523552d36a10",
            "sourceColumn": "Domain",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fc0ce0bf-f023-406c-9873-d22cef86f976",
        "partitions": [
          {
            "name": "Customer Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(CurrentServer, CurrentDatabase, [Query=\"SELECT [CustomerKey]#(lf)      ,[GeographyKey]#(lf)      ,[CustomerAlternateKey]#(lf)      ,[Title]#(lf)      ,[FirstName]#(lf)      ,[LastName]#(lf)      ,[BirthDate]#(lf)      ,[MaritalStatus]#(lf)      ,[Gender]#(lf)      ,[EmailAddress]#(lf)      ,[YearlyIncome]#(lf)      ,[TotalChildren]#(lf)      ,[EnglishEducation]#(lf)      ,[EnglishOccupation]#(lf)      ,[HouseOwnerFlag]#(lf)  FROM [dbo].[DimCustomer]\", CreateNavigationProperties=false]),",
                "    #\"Inserted Text After Delimiter\" = Table.AddColumn(Source, \"Domain\", each Text.AfterDelimiter([EmailAddress], \"@\"), type text),",
                "    #\"Extracted Text Before Delimiter\" = Table.TransformColumns(#\"Inserted Text After Delimiter\", {{\"Domain\", each Text.BeforeDelimiter(_, \".com\", {0, RelativePosition.FromEnd}), type text}}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Extracted Text Before Delimiter\",{{\"Domain\", Text.Proper, type text}}),",
                "    #\"Replace Value\" = Table.ReplaceValue(#\"Capitalized Each Word\",\"-\",\" \",Replacer.ReplaceText,{\"Domain\"})",
                "in",
                "    #\"Replace Value\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_3acdb546-8f22-4f5e-9346-fb0821380efb",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f4b38a7f-96ac-4e60-97ab-377a0e306fcc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cee903c4-77db-4c95-b7b0-d87285b822d6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d3284c28-c243-429a-847a-1e94d4736650",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "694e4ef0-f49d-41c5-bd6d-7d85b0b0f37b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cad07def-3c21-4ebd-9695-bb09d0fa759c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "85dd8839-3ad9-400b-97d7-e02360be87e3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "43539751-d247-4dd8-82df-e214ddc41cb7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5a6a34b2-d4c8-4ade-ad0b-4ee38246ede0",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "041f3579-a2f7-4ec4-b343-b9c2d2b9b003",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5cc5c179-cd76-41a7-9224-aa1e3a49e427",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2bc27746-0e23-4793-baf7-dd89dc61a1c0",
                "ordinal": 3
              }
            ],
            "lineageTag": "964a8223-dc5f-49b1-8df3-8e3acff65502"
          }
        ],
        "isHidden": true,
        "lineageTag": "a5c9be83-b626-4314-97e6-da319b62b87f",
        "partitions": [
          {
            "name": "LocalDateTable_3acdb546-8f22-4f5e-9346-fb0821380efb",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Customer Lookup'[BirthDate])), 1, 1), Date(Year(MAX('Customer Lookup'[BirthDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ff83dada-69ef-41a2-86d7-6e41a859cb85",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_54a07bb5-47eb-4eb7-a5d9-f864f5739ef7"
                },
                "isDefault": true,
                "relationship": "cfca05d3-2d55-4d3f-9e6a-1048bda86bc7"
              }
            ]
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd3e3dae-1797-4b11-a793-9b15f70f38e4",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1fac38a9-4047-43bb-a492-c7eafdb4be11",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Start of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "61fe94ee-dc09-4790-85da-71626532898b",
            "sourceColumn": "Start of Year",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_2df8943f-f7d7-4ecb-ba1f-115dada4382b"
                },
                "isDefault": true,
                "relationship": "ca376516-eef8-417f-b315-113b147f830a"
              }
            ]
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7bd6f556-6698-46b7-bbbf-75bff4f77b8a",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Start of Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "2a47175d-35f4-46fc-bde3-be144f702106",
            "sourceColumn": "Start of Quarter",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c6f5922e-0704-441e-86d9-3aea5517a74c"
                },
                "isDefault": true,
                "relationship": "4974fbdb-457e-4a13-aed8-19cf5835e3cc"
              }
            ]
          }
        ],
        "lineageTag": "54cca210-756f-494e-aa11-7d71354b50c8",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Date.FromText(SalesMinimumDate),",
                "    ToListOfDatesSinceSourceDate = List.Dates(",
                "    Source,",
                "    Number.From(#date(2014,02,01))-Number.From(Source),",
                "    #duration(1,0,0,0)",
                "),",
                "    #\"Converted to Table\" = Table.FromList(ToListOfDatesSinceSourceDate, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Converted to Table\",{{\"Column1\", type date}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Column1\", \"Date\"}}),",
                "    #\"Inserted Month Name\" = Table.AddColumn(#\"Renamed Columns\", \"Month Name\", each Date.MonthName([Date]), type text),",
                "    #\"Inserted Month\" = Table.AddColumn(#\"Inserted Month Name\", \"Month\", each Date.Month([Date]), Int64.Type),",
                "    #\"Inserted Start of Year\" = Table.AddColumn(#\"Inserted Month\", \"Start of Year\", each Date.StartOfYear([Date]), type date),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Inserted Start of Year\", \"Year\", each Date.Year([Date]), Int64.Type),",
                "    #\"Inserted Start of Quarter\" = Table.AddColumn(#\"Inserted Year\", \"Start of Quarter\", each Date.StartOfQuarter([Start of Year]), type date)",
                "in",
                "    #\"Inserted Start of Quarter\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_54a07bb5-47eb-4eb7-a5d9-f864f5739ef7",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5c7324dc-f069-42d1-81f6-0f6d583ef67f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f82e0bab-3e3e-4141-86a2-f68f9bac5e74",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "33bac915-1e4c-4581-ac0a-ae234995be07",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "712ae1ca-63c5-4166-899a-55d79433ad9b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "85dabb01-c724-4ecb-b7db-e0c83044b51e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "4cf47ee7-5837-4ee0-8c66-14171171964c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9161a9e1-a9e2-4d18-a683-0b66e6ece343",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "04fe47d9-32d0-4af5-9d61-fc1f1dc4a230",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "0c788778-f21e-4a74-b456-f892218ac247",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "7976f9de-2922-402e-b5bc-bdb81c4dc56b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "78e899c1-241e-4338-8702-6aea707a4274",
                "ordinal": 3
              }
            ],
            "lineageTag": "70716360-bb95-453a-acaa-8e0d896baea1"
          }
        ],
        "isHidden": true,
        "lineageTag": "f31eadfb-5158-4989-a33c-4ffd1a39bab6",
        "partitions": [
          {
            "name": "LocalDateTable_54a07bb5-47eb-4eb7-a5d9-f864f5739ef7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[Date])), 1, 1), Date(Year(MAX('Calendar'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_2df8943f-f7d7-4ecb-ba1f-115dada4382b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "69509078-94c5-4de7-92de-b9931bbf3d48",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "54aabe9c-3f02-42d1-8dbb-184bd1602bba",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f69ca30e-8e3d-4150-b341-bfdd313d1d05",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "21a7d730-e6a7-4824-a83b-5856336a5e03",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3783cbba-792f-45f4-abc8-c6d08c499278",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5e75d0cc-6595-411b-9a14-948258e7b0b5",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4e809105-b917-4ffc-b3bd-db8b0a98b290",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "369966e3-3db9-42a3-8061-23e84416feb1",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "cbc3d5b7-2349-4560-b189-a05f7096f496",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b9c67197-1f66-4528-9f60-682a5e646e4c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e08a04e6-35cd-428d-885e-5798669612c7",
                "ordinal": 3
              }
            ],
            "lineageTag": "9aa74943-7826-4301-bfc4-338dbbfe3a11"
          }
        ],
        "isHidden": true,
        "lineageTag": "2f0067a3-51d3-404d-842b-2d9fa4aea617",
        "partitions": [
          {
            "name": "LocalDateTable_2df8943f-f7d7-4ecb-ba1f-115dada4382b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[Start of Year])), 1, 1), Date(Year(MAX('Calendar'[Start of Year])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_c6f5922e-0704-441e-86d9-3aea5517a74c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0af6c255-c592-404c-ae36-f6667e135c3f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "595bf614-68cd-448d-b744-1f3188d89c1d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c751c9fd-5c04-40ea-bdff-0f53faaaac48",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "185973ed-bb3f-481d-9788-912e688827b4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "87c10265-989a-418e-9c64-ec9d1860543c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "bade2d4c-fe1d-4e85-8d15-417b6814082e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d8486009-50cf-4658-918b-7a4e7c96b4bd",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "437760dd-dda7-4628-bd22-ca6447a8f092",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "798668c1-4579-4f4d-b189-c3eb73877959",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b3691c8f-77b2-4bf6-93ef-ba78bc2ab452",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "3526dc32-9e2b-487a-9d4e-2183e230874b",
                "ordinal": 3
              }
            ],
            "lineageTag": "8b5a96d3-df43-4942-b4ef-f810c1d36024"
          }
        ],
        "isHidden": true,
        "lineageTag": "e9725f8c-f7c5-48e3-b8ce-2b1a49a5a6b2",
        "partitions": [
          {
            "name": "LocalDateTable_c6f5922e-0704-441e-86d9-3aea5517a74c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[Start of Quarter])), 1, 1), Date(Year(MAX('Calendar'[Start of Quarter])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Internet Sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "85df5edd-6083-4fe3-89fd-84a68c88b2be",
            "sourceColumn": "ProductKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "OrderDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "102b25a4-96d3-4016-b91f-a69c52d2287b",
            "sourceColumn": "OrderDateKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "DueDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "259e58e9-b2ca-4310-b7f5-a10b58ff4630",
            "sourceColumn": "DueDateKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "ShipDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "2cc9d6c7-bead-46ed-8c62-02f697ef4602",
            "sourceColumn": "ShipDateKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "12c438e2-c2fd-4560-8d79-0ae122030c14",
            "sourceColumn": "CustomerKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "PromotionKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "b64c0111-8f9a-47e7-8ab9-be5397e36fa7",
            "sourceColumn": "PromotionKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "CurrencyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "92aa0147-8a9a-47f4-b05e-fb300809e2eb",
            "sourceColumn": "CurrencyKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "SalesTerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "2d42ea3b-6914-4b33-a0c4-142bb049215d",
            "sourceColumn": "SalesTerritoryKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "SalesOrderNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "cb8241a8-278c-4cec-9202-a4f6a096943c",
            "sourceColumn": "SalesOrderNumber",
            "sourceProviderType": "nvarchar(20)",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderLineNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "a0ba78f2-63f6-42b5-8587-b9e65bc49072",
            "sourceColumn": "SalesOrderLineNumber",
            "sourceProviderType": "tinyint",
            "summarizeBy": "sum"
          },
          {
            "name": "RevisionNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "94282513-fa7f-4d80-af36-62e79fcafdaf",
            "sourceColumn": "RevisionNumber",
            "sourceProviderType": "tinyint",
            "summarizeBy": "sum"
          },
          {
            "name": "OrderQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "a0102ee0-112b-42ac-a477-726eabfcce85",
            "sourceColumn": "OrderQuantity",
            "sourceProviderType": "smallint",
            "summarizeBy": "sum"
          },
          {
            "name": "UnitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "1f68f841-b70c-42a6-a508-003700d51f3a",
            "sourceColumn": "UnitPrice",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "ExtendedAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "d696847c-ae61-4d86-b478-48965f3fcf45",
            "sourceColumn": "ExtendedAmount",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "UnitPriceDiscountPct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "f2957868-465a-4abd-aec4-2c35c3985004",
            "sourceColumn": "UnitPriceDiscountPct",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "DiscountAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "21f524ea-6ff1-4fd6-b866-0c7454360632",
            "sourceColumn": "DiscountAmount",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductStandardCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "35eb8c58-fa2d-476e-859a-0b7ab815c2ce",
            "sourceColumn": "ProductStandardCost",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalProductCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "ef4d8d77-eb36-426e-8b9c-2bc70e0a8224",
            "sourceColumn": "TotalProductCost",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "SalesAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "f6e14012-6294-442b-a9a4-3ac82b7b03d1",
            "sourceColumn": "SalesAmount",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "TaxAmt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "c77039e3-436f-4bcf-95bf-0294664db787",
            "sourceColumn": "TaxAmt",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "Freight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isNullable": false,
            "lineageTag": "1b7e21a8-5084-4cd7-9d44-e7d1581f4d5b",
            "sourceColumn": "Freight",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "CarrierTrackingNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88ccd34b-030f-40df-a1f6-e6b96e9025b8",
            "sourceColumn": "CarrierTrackingNumber",
            "sourceProviderType": "nvarchar(25)",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerPONumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "870d8903-ff6f-44e0-8395-e95e3943dd3e",
            "sourceColumn": "CustomerPONumber",
            "sourceProviderType": "nvarchar(25)",
            "summarizeBy": "none"
          },
          {
            "name": "OrderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "3a7fed7a-a56d-4b42-bf90-176130411612",
            "sourceColumn": "OrderDate",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_d4a38875-966c-4add-b851-15addb1ccf37"
                },
                "isDefault": true,
                "relationship": "781f44d5-5ccb-42e3-aefd-429837ec2266"
              }
            ]
          },
          {
            "name": "DueDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "3cfbfd08-2f13-44f9-92a6-3ae826fe5df4",
            "sourceColumn": "DueDate",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_1080db56-9b62-43c7-aab3-369e2bcfd477"
                },
                "isDefault": true,
                "relationship": "4750832d-7172-4883-8254-4bc74e24cb11"
              }
            ]
          },
          {
            "name": "ShipDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "00c20e93-5163-45c7-85f9-2d88ad48b01f",
            "sourceColumn": "ShipDate",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e2a3474b-1858-47bf-91f7-d73bed853a8c"
                },
                "isDefault": true,
                "relationship": "7c6950ca-b538-4505-99bc-8952a4067ea3"
              }
            ]
          }
        ],
        "lineageTag": "ae668abf-a312-483c-b659-989e1afbecbf",
        "partitions": [
          {
            "name": "Internet Sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(CurrentServer, CurrentDatabase, [Query=\"SELECT [ProductKey]#(lf)      ,[OrderDateKey]#(lf)      ,[DueDateKey]#(lf)      ,[ShipDateKey]#(lf)      ,[CustomerKey]#(lf)      ,[PromotionKey]#(lf)      ,[CurrencyKey]#(lf)      ,[SalesTerritoryKey]#(lf)      ,[SalesOrderNumber]#(lf)      ,[SalesOrderLineNumber]#(lf)      ,[RevisionNumber]#(lf)      ,[OrderQuantity]#(lf)      ,[UnitPrice]#(lf)      ,[ExtendedAmount]#(lf)      ,[UnitPriceDiscountPct]#(lf)      ,[DiscountAmount]#(lf)      ,[ProductStandardCost]#(lf)      ,[TotalProductCost]#(lf)      ,[SalesAmount]#(lf)      ,[TaxAmt]#(lf)      ,[Freight]#(lf)      ,[CarrierTrackingNumber]#(lf)      ,[CustomerPONumber]#(lf)      ,[OrderDate]#(lf)      ,[DueDate]#(lf)      ,[ShipDate]#(lf)  FROM [dbo].[FactInternetSales]#(lf)  WHERE [OrderDate] >= '\"&SalesMinimumDate&\"'\", CreateNavigationProperties=false])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Reseller Sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "e3de920f-dab6-4dee-988f-cb1f24077c37",
            "sourceColumn": "ProductKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "OrderDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "e60f0943-7faf-4557-863e-1314f6e4c510",
            "sourceColumn": "OrderDateKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "DueDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "a2d3a642-40cd-4a3f-be2e-2feb1407b323",
            "sourceColumn": "DueDateKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "ShipDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "e99c01fc-a9aa-42fd-9672-996d5455108f",
            "sourceColumn": "ShipDateKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "f4910973-13f8-40a1-a50b-98c32587aaf2",
            "sourceColumn": "CustomerKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "PromotionKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "f50d8dfa-5936-4eed-aa07-8436c005c462",
            "sourceColumn": "PromotionKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "CurrencyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "17c4e190-3ac4-4a66-bfdb-8fbfe947ad27",
            "sourceColumn": "CurrencyKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "SalesTerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "87e1e6f1-7ebb-41f5-a273-70c3b2dbdd03",
            "sourceColumn": "SalesTerritoryKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "SalesOrderNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "502d0870-b5d2-47a0-9be3-ae0f356c6106",
            "sourceColumn": "SalesOrderNumber",
            "sourceProviderType": "nvarchar(20)",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderLineNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "882e10fd-71b5-46b5-afe8-1dc754cfc08f",
            "sourceColumn": "SalesOrderLineNumber",
            "sourceProviderType": "tinyint",
            "summarizeBy": "sum"
          },
          {
            "name": "RevisionNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f6d551c2-97f7-475d-ba65-747adbc52a5f",
            "sourceColumn": "RevisionNumber",
            "sourceProviderType": "tinyint",
            "summarizeBy": "sum"
          },
          {
            "name": "OrderQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0d0e3863-a5ad-4bd5-8073-ef0ce2f646dc",
            "sourceColumn": "OrderQuantity",
            "sourceProviderType": "smallint",
            "summarizeBy": "sum"
          },
          {
            "name": "UnitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a70e299e-3120-416f-9b14-b1ec7e73252c",
            "sourceColumn": "UnitPrice",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "ExtendedAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "19a6dc49-db33-4843-a072-b592f6c74864",
            "sourceColumn": "ExtendedAmount",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "UnitPriceDiscountPct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0b1275d1-c7a5-4ad9-98fd-9824a4de4836",
            "sourceColumn": "UnitPriceDiscountPct",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "DiscountAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "15cb24a8-9012-4566-9501-e1d30828f07b",
            "sourceColumn": "DiscountAmount",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductStandardCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d116bb42-9c92-4b67-8bfc-eba8241cb499",
            "sourceColumn": "ProductStandardCost",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalProductCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2d851dd2-c4f8-4258-b89e-ff66352b3e8b",
            "sourceColumn": "TotalProductCost",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "SalesAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dfa90cce-25c4-4079-9ecf-7ff15a3ad4a2",
            "sourceColumn": "SalesAmount",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "TaxAmt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "565dfe45-bf76-46d6-8161-b6852f7cb0c8",
            "sourceColumn": "TaxAmt",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "Freight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c4c9e255-1a17-4c0f-884f-7968456b80f4",
            "sourceColumn": "Freight",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "CarrierTrackingNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea469a46-5242-403a-9498-2417ed1b9a96",
            "sourceColumn": "CarrierTrackingNumber",
            "sourceProviderType": "nvarchar(25)",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerPONumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "851deeb9-5e3b-4181-a3b9-0a6c9a5da9ed",
            "sourceColumn": "CustomerPONumber",
            "sourceProviderType": "nvarchar(25)",
            "summarizeBy": "none"
          },
          {
            "name": "OrderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "e321e6eb-0ba8-4768-b67f-0ede19c75294",
            "sourceColumn": "OrderDate",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_8926865d-b7b2-48e8-953a-652fd20ab5d2"
                },
                "isDefault": true,
                "relationship": "c70bdd04-796e-493f-aa3e-fcc8cc052779"
              }
            ]
          },
          {
            "name": "DueDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "f9c83404-a511-4bd8-b15d-a356f3d5e6e5",
            "sourceColumn": "DueDate",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_433f3959-dd6b-49bf-b184-1d41229b4926"
                },
                "isDefault": true,
                "relationship": "7c569d3e-d609-43e6-9812-2adc36b86b84"
              }
            ]
          },
          {
            "name": "ShipDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "8a24a400-bfe8-4db8-b568-dca937fe0f76",
            "sourceColumn": "ShipDate",
            "sourceProviderType": "datetime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a0ff8239-4169-4262-8605-6db69c81c6c0"
                },
                "isDefault": true,
                "relationship": "a3f786ac-2136-4576-8f95-1f7f21c16507"
              }
            ]
          }
        ],
        "lineageTag": "939d6717-18fb-43f8-a940-ee9c4068f11d",
        "partitions": [
          {
            "name": "Reseller Sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(CurrentServer, CurrentDatabase, [Query=\"SELECT [ProductKey]#(lf)      ,[OrderDateKey]#(lf)      ,[DueDateKey]#(lf)      ,[ShipDateKey]#(lf)      ,[ResellerKey] as [CustomerKey]--,[EmployeeKey]#(lf)      ,[PromotionKey]#(lf)      ,[CurrencyKey]#(lf)      ,[SalesTerritoryKey]#(lf)      ,[SalesOrderNumber]#(lf)      ,[SalesOrderLineNumber]#(lf)      ,[RevisionNumber]#(lf)      ,[OrderQuantity]#(lf)      ,[UnitPrice]#(lf)      ,[ExtendedAmount]#(lf)      ,[UnitPriceDiscountPct]#(lf)      ,[DiscountAmount]#(lf)      ,[ProductStandardCost]#(lf)      ,[TotalProductCost]#(lf)      ,[SalesAmount]#(lf)      ,[TaxAmt]#(lf)      ,[Freight]#(lf)      ,[CarrierTrackingNumber]#(lf)      ,[CustomerPONumber]#(lf)      ,[OrderDate]#(lf)      ,[DueDate]#(lf)      ,[ShipDate]#(lf)  FROM [dbo].[FactResellerSales]#(lf)  WHERE [OrderDate] >= '\"&SalesMinimumDate&\"'\", CreateNavigationProperties=false])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_b8db72a3-b675-44d9-9220-a6793d123884",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f1852c72-e1b3-4424-a5b3-7765a4d7148b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b848593e-775a-46a2-9b24-d219e130ad55",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "48a2a49d-b095-421a-b142-b1988aef12d2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8d3134a7-5dba-49e7-bceb-07249302e5ea",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "87ef3b71-3015-438b-9e48-98bc6de06041",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "e34e7d7a-a9f8-4e7f-8740-d984e0dabecd",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c2fa529c-c933-4a60-b1f4-27ca27e57548",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ce5fe4d1-1c6d-4b73-82d2-188686a7b467",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "323da97c-9b8e-40fd-9538-1c9b1a0e0d9e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c3204dad-4869-456a-a13d-37ba2a68212f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e43abda4-f77a-4894-8319-4b9a1c2c8a5c",
                "ordinal": 3
              }
            ],
            "lineageTag": "f8d12df1-3d27-4dc8-8e11-85ee42553339"
          }
        ],
        "isHidden": true,
        "lineageTag": "84b07cb7-b79d-4ead-a05d-fba4b2c760e2",
        "partitions": [
          {
            "name": "LocalDateTable_b8db72a3-b675-44d9-9220-a6793d123884",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Customer Lookup DQ'[BirthDate])), 1, 1), Date(Year(MAX('Customer Lookup DQ'[BirthDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_d4a38875-966c-4add-b851-15addb1ccf37",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6deb1ba5-f007-4540-93cc-9006e34c3358",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c428db25-da7f-4fd6-8739-2014e9b388ca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "16bf9c7b-c7fb-4acf-920e-06481d70e4f7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "362b15f4-84b5-49ea-bb10-44e187b3abe4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "31ea5525-11c7-4e57-b9e5-851430f6ebcb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "330ba6a3-f1d2-4fe1-ad49-66b0f7ae9519",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "30073f88-a778-4f45-8acf-b4de934ed81d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9bc2c2d8-7861-473e-87fa-ffac7848cca0",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "addd546e-d344-4eb2-8bd7-b821366ee264",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "68e5734c-ff8c-47be-a0d3-a5a468bb25ee",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "28c3d652-141e-4a71-896b-0228dc05ec71",
                "ordinal": 3
              }
            ],
            "lineageTag": "3165e55e-23d2-48ab-b2a6-59d432a92366"
          }
        ],
        "isHidden": true,
        "lineageTag": "9d6c95bb-0f1f-4db0-82f6-48c27e574181",
        "partitions": [
          {
            "name": "LocalDateTable_d4a38875-966c-4add-b851-15addb1ccf37",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Internet Sales'[OrderDate])), 1, 1), Date(Year(MAX('Internet Sales'[OrderDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_1080db56-9b62-43c7-aab3-369e2bcfd477",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "656685d8-e41c-45a3-a97b-4258bde6a9f3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "31075dae-5f85-4171-bccb-ef4a4643093d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9ed6e162-117c-4d0c-8846-fa5bfd84b85a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f1c0a30f-3508-4f6e-811c-4243fe020af2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "35696b36-121a-4c2b-8204-565603cd45dc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5dd97923-1a1c-4fe3-99ce-bfa4208ceca2",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "98944afb-4101-4a3d-9c25-8799ea4c8398",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "bb506158-1c8e-4727-8cf2-37d6f4c6650a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "81d09c1c-bfd0-4476-a528-032b2fbd054f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "894e5825-f67d-405d-bf25-a749370b82c0",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "86f1b60f-792f-4aec-b89f-3c1a68d235df",
                "ordinal": 3
              }
            ],
            "lineageTag": "2ec5490b-34a3-4dbb-919c-a1ee51c94f71"
          }
        ],
        "isHidden": true,
        "lineageTag": "8bd2f2bd-9b15-4e37-9253-b947e1995964",
        "partitions": [
          {
            "name": "LocalDateTable_1080db56-9b62-43c7-aab3-369e2bcfd477",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Internet Sales'[DueDate])), 1, 1), Date(Year(MAX('Internet Sales'[DueDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e2a3474b-1858-47bf-91f7-d73bed853a8c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e79a336a-bb75-41ce-a912-9aef3da3b618",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ca64fcb8-7768-4e22-862b-30df1cbe518e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2acce6b1-ecb0-4354-8ab1-580bfac1bbee",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ef2d2469-a5b1-4b18-8282-d0817092e422",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "209881ba-aa45-4b25-a0ee-a846c499d038",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "67e64689-8d7b-4431-8794-9c25ae5b551c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "083a8efa-b052-4a01-bd68-0ed84feee18f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f6e0bde0-29ce-4592-bfad-2bf2f0f27607",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "84e17390-03d5-450d-8b55-fb2457cd63dd",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "382c4308-efb8-4c76-bbb9-d3a649b62b6f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d999297d-ff5e-4c20-9d96-2c9ac024018f",
                "ordinal": 3
              }
            ],
            "lineageTag": "7757534b-6c4e-4646-8f07-90ce792968f7"
          }
        ],
        "isHidden": true,
        "lineageTag": "c8845c3c-e268-4958-8126-d5ef3f953f69",
        "partitions": [
          {
            "name": "LocalDateTable_e2a3474b-1858-47bf-91f7-d73bed853a8c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Internet Sales'[ShipDate])), 1, 1), Date(Year(MAX('Internet Sales'[ShipDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_8926865d-b7b2-48e8-953a-652fd20ab5d2",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d9b8da9a-5f61-4f50-909a-a8e9c0c0dc07",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ffac731f-0fbd-41c0-9ea7-93ad6df8bafb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "401ef192-800a-41b6-9fd1-7e606f1e613b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "dea12ea3-d19c-4c6a-9b9e-9142b3f0a0fb",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "918c0124-d13b-44ab-985d-428aea1a3083",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "0245c800-6653-4400-b054-4f2e6aeec053",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7a8a1c03-51bf-4533-9b73-01b4a0c5bc69",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "485e0608-04e3-4ddd-94a9-5ab3e387b5ac",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "75ffd88c-8530-4226-ba3b-9cc09b3eb93b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "914cb989-0ba3-44aa-bd6a-7caf270489e0",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0d75eba5-b89a-4880-9bd6-096ac6dda92d",
                "ordinal": 3
              }
            ],
            "lineageTag": "b8d7f84b-2123-4fcb-b970-c5387b460e17"
          }
        ],
        "isHidden": true,
        "lineageTag": "e5f802cc-eab7-4999-9f33-39aaca8e132d",
        "partitions": [
          {
            "name": "LocalDateTable_8926865d-b7b2-48e8-953a-652fd20ab5d2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Reseller Sales'[OrderDate])), 1, 1), Date(Year(MAX('Reseller Sales'[OrderDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_433f3959-dd6b-49bf-b184-1d41229b4926",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "599f1ed3-f15f-4fab-a576-adb2eb6b7cc3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "71701955-455e-43a8-b8ac-9ab5d391e2c2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b2a4cbcd-f904-4e91-ab42-df798bb57bf0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "319ebe89-cb4a-4946-9b6c-6c3b6c237943",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0fbe8b60-2a3d-4dcb-84cf-10f8559f950e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "440067e8-cad8-41d5-82d5-7bf58e3c4082",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7b36c372-5baa-44e0-bb70-53eaf7f25f47",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "6a7f37be-7e8a-45e0-93cb-a8981440aafb",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f7ec968f-032b-408b-aff7-195cd23053ce",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e1c4c769-ae93-499a-8597-e253ca0b7de4",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "dab1bcba-5d4a-4150-872a-68de14594800",
                "ordinal": 3
              }
            ],
            "lineageTag": "c945d99e-f629-4f47-b1da-bbe813b1a126"
          }
        ],
        "isHidden": true,
        "lineageTag": "74708a96-2dbf-4004-8199-24de32839078",
        "partitions": [
          {
            "name": "LocalDateTable_433f3959-dd6b-49bf-b184-1d41229b4926",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Reseller Sales'[DueDate])), 1, 1), Date(Year(MAX('Reseller Sales'[DueDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_a0ff8239-4169-4262-8605-6db69c81c6c0",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e441bae0-54f6-4dcc-bb35-ee2453784aed",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a51d01e2-e8fa-401d-b1ed-49627dadb141",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2e25052c-25d8-487c-9d82-419cd2a865f9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1f401471-67a2-4f36-a2c2-d1a563216a70",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b0b43dd0-43e4-4f4d-993a-80a5f12defd3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f29de910-ff53-42de-93a4-5cc759ae23ac",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b00b9c3a-55f7-4f4d-80d8-26bd699b6f74",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0f1adf91-09ff-45a7-9a4d-1d7a0a0b783a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "901a2782-877b-4e0c-ba2f-df431a98729d",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c534152c-34ba-4e04-ae3c-3147caa0c1b1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e4e76505-a7ab-477f-90f8-7dae890fb7b0",
                "ordinal": 3
              }
            ],
            "lineageTag": "8782fe40-e346-471a-9252-b629e2792783"
          }
        ],
        "isHidden": true,
        "lineageTag": "d3ba57c0-50e9-4cf9-9da6-1f50f7cc4085",
        "partitions": [
          {
            "name": "LocalDateTable_a0ff8239-4169-4262-8605-6db69c81c6c0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Reseller Sales'[ShipDate])), 1, 1), Date(Year(MAX('Reseller Sales'[ShipDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}