{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1554.0 (23.12)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Territory Lookup\",\"Product Lookup\",\"Product Category Lookup\",\"Product Subcategory Lookup\",\"Customer Lookup DQ\",\"Customer Lookup\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "9c97e787-2f56-4189-9a80-b9670f16f6e1",
        "fromColumn": "StartDate",
        "fromTable": "Product Lookup",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_8b4d6d0e-bc68-481e-9282-8a182ecf2e4e"
      },
      {
        "name": "e592823b-cb03-4eae-b65b-afb972e0a8c9",
        "fromColumn": "EndDate",
        "fromTable": "Product Lookup",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_42528443-5a4c-4a07-b0b4-7c7d97e55e0c"
      },
      {
        "name": "4a1502c3-bc15-498d-8955-ba41c3c58fdd",
        "fromColumn": "BirthDate",
        "fromTable": "Customer Lookup",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3acdb546-8f22-4f5e-9346-fb0821380efb"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Product Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "186f1686-e1ba-4c62-91e5-a6c969957664",
            "sourceColumn": "ProductKey",
            "summarizeBy": "count"
          },
          {
            "name": "ProductAlternateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1bb3c26-69e4-460f-9349-07a7cd63485e",
            "sourceColumn": "ProductAlternateKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSubcategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "96ee21c5-c126-46ba-9c5e-da6e5b01cfae",
            "sourceColumn": "ProductSubcategoryKey",
            "summarizeBy": "count"
          },
          {
            "name": "WeightUnitMeasureCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "282c45a8-e439-495f-bdc0-1c8e57abca61",
            "sourceColumn": "WeightUnitMeasureCode",
            "summarizeBy": "none"
          },
          {
            "name": "SizeUnitMeasureCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9de19186-0bba-4338-8ac8-f02a70072374",
            "sourceColumn": "SizeUnitMeasureCode",
            "summarizeBy": "none"
          },
          {
            "name": "EnglishProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c04867cb-0aaf-4357-81fd-de35b02dfb84",
            "sourceColumn": "EnglishProductName",
            "summarizeBy": "none"
          },
          {
            "name": "StandardCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bccfd3f5-3504-48a6-a149-e2d7c728e346",
            "sourceColumn": "StandardCost",
            "summarizeBy": "sum"
          },
          {
            "name": "FinishedGoodsFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "13bc9201-60c5-48ae-a760-c9fbc873faf1",
            "sourceColumn": "FinishedGoodsFlag",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8007225a-e547-4aff-93b7-76916f2d40fb",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "SafetyStockLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e31418a1-1651-4a82-b7f0-c22cf2c60fdf",
            "sourceColumn": "SafetyStockLevel",
            "summarizeBy": "sum"
          },
          {
            "name": "ReorderPoint",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d5284fd2-01b3-4e37-9c5d-7bcf9a95414c",
            "sourceColumn": "ReorderPoint",
            "summarizeBy": "sum"
          },
          {
            "name": "ListPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "af8be974-3a36-4953-a2b3-8f5c1f4790aa",
            "sourceColumn": "ListPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "Size",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "daf9df69-6c88-40b0-8673-c960862ae2d8",
            "sourceColumn": "Size",
            "summarizeBy": "none"
          },
          {
            "name": "SizeRange",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c938784a-4887-4917-9b65-924258b74798",
            "sourceColumn": "SizeRange",
            "summarizeBy": "none"
          },
          {
            "name": "Weight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "183f57af-7d25-4a08-81d2-b3233b72d939",
            "sourceColumn": "Weight",
            "summarizeBy": "sum"
          },
          {
            "name": "DaysToManufacture",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c7c236ba-c4f9-4770-8ab8-7560d7baa3e4",
            "sourceColumn": "DaysToManufacture",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductLine",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "37373eed-2e89-46a8-8dcd-24ba80b1f0aa",
            "sourceColumn": "ProductLine",
            "summarizeBy": "none"
          },
          {
            "name": "DealerPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "f796d627-c3f4-4e7b-a52d-ea344010961d",
            "sourceColumn": "DealerPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "Class",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8838e61-c0a6-4e81-b8cb-c0e8bd001941",
            "sourceColumn": "Class",
            "summarizeBy": "none"
          },
          {
            "name": "Style",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33da15f9-7067-456a-a591-fa91ccbf563f",
            "sourceColumn": "Style",
            "summarizeBy": "none"
          },
          {
            "name": "ModelName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "719abc57-8dd5-41a0-8599-bb8c19f9fa83",
            "sourceColumn": "ModelName",
            "summarizeBy": "none"
          },
          {
            "name": "EnglishDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9088e8dd-9dc3-448e-871c-7562b926e39b",
            "sourceColumn": "EnglishDescription",
            "summarizeBy": "none"
          },
          {
            "name": "StartDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "834bc9f9-a1e9-49ac-8fd7-2c830321de62",
            "sourceColumn": "StartDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_8b4d6d0e-bc68-481e-9282-8a182ecf2e4e"
                },
                "isDefault": true,
                "relationship": "9c97e787-2f56-4189-9a80-b9670f16f6e1"
              }
            ]
          },
          {
            "name": "EndDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "71247f4d-d6ac-4106-a24b-e669ba5fb94c",
            "sourceColumn": "EndDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_42528443-5a4c-4a07-b0b4-7c7d97e55e0c"
                },
                "isDefault": true,
                "relationship": "e592823b-cb03-4eae-b65b-afb972e0a8c9"
              }
            ]
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "374daf24-92af-4fe5-a93e-6a373886d7a7",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "SKU Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90c65f31-f38e-4fb1-93f1-8eade76be163",
            "sourceColumn": "SKU Type",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8b3e7ffb-fbaa-450a-87f6-835000331cc1",
        "partitions": [
          {
            "name": "Product Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"AdventureWorksDW2019\", [Query=\"SELECT [ProductKey]#(lf)      ,[ProductAlternateKey]#(lf)      ,[ProductSubcategoryKey]#(lf)      ,[WeightUnitMeasureCode]#(lf)      ,[SizeUnitMeasureCode]#(lf)      ,[EnglishProductName]#(lf)      ,[StandardCost]#(lf)      ,[FinishedGoodsFlag]#(lf)      ,[Color]#(lf)      ,[SafetyStockLevel]#(lf)      ,[ReorderPoint]#(lf)      ,[ListPrice]#(lf)      ,[Size]#(lf)      ,[SizeRange]#(lf)      ,[Weight]#(lf)      ,[DaysToManufacture]#(lf)      ,[ProductLine]#(lf)      ,[DealerPrice]#(lf)      ,[Class]#(lf)      ,[Style]#(lf)      ,[ModelName]#(lf)      ,[LargePhoto]#(lf)      ,[EnglishDescription]#(lf)      ,[StartDate]#(lf)      ,[EndDate]#(lf)      ,[Status]#(lf)  FROM [dbo].[DimProduct]\", CreateNavigationProperties=false]),",
                "    #\"Change to Currency\" = Table.TransformColumnTypes(Source,{{\"DealerPrice\", Currency.Type}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Change to Currency\", \"SKU Type\", each ",
                "Text.BeforeDelimiter([ProductAlternateKey],\"-\",1)",
                "    ),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Added Custom\", each true),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Filtered Rows\",null,\"N/A\",Replacer.ReplaceValue,{\"Style\"})",
                "in",
                "    #\"Replaced Value\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_18e443f7-20a5-47af-9af7-99b1a1710446",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "75c32deb-98aa-4f24-99b9-02e51fe5ba55",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3124bed7-95bd-47cb-999c-58fcda0bab0d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "91704f19-319b-4f1e-9d8c-39ad04f63622",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "bd324b19-ac2f-457a-b519-72e622d86cd8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8890d8f6-449f-4473-8c83-52cd09a2232a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "b303b0bc-7cad-41c5-9fee-3901552234a3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "788f1c91-fdb3-4d88-810d-2a5295571114",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "304e7536-f769-4ddb-acd0-675b0520c95c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "92aad8a1-99fd-4223-92b3-648ba7c77a5f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6bc1dd00-5158-4929-b0ce-a023e571fcc3",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b3672a2e-279c-441b-b3ea-fbdbf53b2b04",
                "ordinal": 3
              }
            ],
            "lineageTag": "901b7c47-8f9a-4a33-93c9-f2f461029df1"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "619da7f9-58f5-44b0-ac79-a674e7a6e9f0",
        "partitions": [
          {
            "name": "DateTableTemplate_18e443f7-20a5-47af-9af7-99b1a1710446",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_8b4d6d0e-bc68-481e-9282-8a182ecf2e4e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9eb8a4ce-0d67-455c-af6a-23330e1159ac",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c25f6e26-f5f9-41c3-a12a-250665717219",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e0ac8285-a0dc-4d3e-8523-a19d13ec0b9f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8ed6874e-7bfd-4339-a6e2-99455740c2ad",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f8ffb003-4101-4d65-b337-16523d0dc436",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "892f668a-ddfc-489a-99c8-3e8522697ea7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d52395e7-c0a5-4f8d-a76f-c17d7267ab43",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "336af349-2ed1-45ee-8b7c-b20f5e1415ec",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "aada1db7-a14b-453e-b652-168e5544c6a5",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "461a7f34-cdf2-4344-9190-7527d0c341a5",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1704d0af-e220-436d-b2bc-f528c9ee581d",
                "ordinal": 3
              }
            ],
            "lineageTag": "53e435d2-1d2a-4c45-954a-282f4a97ff9f"
          }
        ],
        "isHidden": true,
        "lineageTag": "841b3d4b-6e62-4fb6-a410-68d56c6f6c67",
        "partitions": [
          {
            "name": "LocalDateTable_8b4d6d0e-bc68-481e-9282-8a182ecf2e4e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Product Lookup'[StartDate])), 1, 1), Date(Year(MAX('Product Lookup'[StartDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_42528443-5a4c-4a07-b0b4-7c7d97e55e0c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "22f9106b-b5b3-496e-8863-b3413b6bbf00",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "20bc374d-5f07-4977-9701-f97d9cfe4d18",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d8967f81-a3ae-4033-abc6-5f9464d75ae2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6a28ff8e-8f92-45bf-a37c-1e7af717f677",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8a5707cb-6ef9-4020-9d8b-d8186e94a677",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "aa54e3fe-6c94-4830-b7a4-1fcf468c30fb",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "adfbd3fa-a95b-452c-a5f8-525c9f7fbc64",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7bd6ea64-91df-4262-bf37-b1ddbff270f3",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a04c5851-cff9-4678-b295-f5762b989575",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "99cf5831-0bea-4f68-bdef-11897bf2a524",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "9a020a59-d3ab-4412-b825-63fb13235327",
                "ordinal": 3
              }
            ],
            "lineageTag": "5a69d75d-4389-4a9f-9db4-29fa731e574d"
          }
        ],
        "isHidden": true,
        "lineageTag": "73767954-7be7-40a5-963e-5ed1a96caee5",
        "partitions": [
          {
            "name": "LocalDateTable_42528443-5a4c-4a07-b0b4-7c7d97e55e0c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Product Lookup'[EndDate])), 1, 1), Date(Year(MAX('Product Lookup'[EndDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Territory Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SalesTerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "07b2f2d7-e82b-4d3d-b1a5-8ba26a31487c",
            "sourceColumn": "SalesTerritoryKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "SalesTerritoryAlternateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "636194c4-ee1a-45e8-99a7-a0b584681528",
            "sourceColumn": "SalesTerritoryAlternateKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "SalesTerritoryRegion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "ae48f413-02a5-471b-b3a6-2acfbfe427f9",
            "sourceColumn": "SalesTerritoryRegion",
            "sourceProviderType": "nvarchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryCountry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "44cc98c1-b3c6-4159-b91d-f4fd7665d257",
            "sourceColumn": "SalesTerritoryCountry",
            "sourceProviderType": "nvarchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "654cd5fe-587c-45db-ae0b-426897d9a06b",
            "sourceColumn": "SalesTerritoryGroup",
            "sourceProviderType": "nvarchar(50)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bfdfb20c-bee9-42e6-9df3-9d26346163ad",
        "partitions": [
          {
            "name": "Territory Lookup",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"AdventureWorksDW2019\", [Query=\"SELECT [SalesTerritoryKey]#(lf)      ,[SalesTerritoryAlternateKey]#(lf)      ,[SalesTerritoryRegion]#(lf)      ,[SalesTerritoryCountry]#(lf)      ,[SalesTerritoryGroup]#(lf)      ,[SalesTerritoryImage]#(lf)  FROM [dbo].[DimSalesTerritory]\", CreateNavigationProperties=false])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product Category Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductCategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "42fc53e2-3126-4b95-a482-5d22e39bf768",
            "sourceColumn": "ProductCategoryKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "CategoryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "83d34ccc-58ea-4eda-a670-beaa453d80db",
            "sourceColumn": "CategoryName",
            "sourceProviderType": "nvarchar(50)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ea63aa7e-c557-4d25-b46b-b5752aa12a52",
        "partitions": [
          {
            "name": "Product Category Lookup",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"AdventureWorksDW2019\", [Query=\"SELECT [ProductCategoryKey]#(lf)      ,[EnglishProductCategoryName] as [CategoryName]#(lf)  FROM [AdventureWorksDW2019].[dbo].[DimProductCategory]\", CreateNavigationProperties=false])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product Subcategory Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductSubcategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "d6742f97-7212-477e-a88d-65854e461541",
            "sourceColumn": "ProductSubcategoryKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "SubcategoryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "7de1a814-4bc7-4f6b-bdee-f7869cee7e4b",
            "sourceColumn": "SubcategoryName",
            "sourceProviderType": "nvarchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6f5b81aa-8962-416a-a515-a34e4a003764",
            "sourceColumn": "ProductCategoryKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "386fe30e-6c1b-499b-9214-976de88c305c",
        "partitions": [
          {
            "name": "Product Subcategory Lookup",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"AdventureWorksDW2019\", [Query=\"SELECT [ProductSubcategoryKey]#(lf)      ,[EnglishProductSubcategoryName] as [SubcategoryName]#(lf)      ,[ProductCategoryKey]#(lf)  FROM [AdventureWorksDW2019].[dbo].[DimProductSubcategory]\", CreateNavigationProperties=false])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer Lookup DQ",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "dbb818c6-fb40-48cb-a20a-3130c97b44fc",
            "sourceColumn": "CustomerKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "GeographyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "545180f4-1f99-4829-a11c-412608c96987",
            "sourceColumn": "GeographyKey",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "CustomerAlternateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "a98620fd-ffe6-48d4-9f43-db7e89cb82e2",
            "sourceColumn": "CustomerAlternateKey",
            "sourceProviderType": "nvarchar(15)",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b66886e-4df2-4aae-8dc3-12623ae1173b",
            "sourceColumn": "Title",
            "sourceProviderType": "nvarchar(8)",
            "summarizeBy": "none"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "261dd9a9-bbe2-4338-ac8a-58428ef1184b",
            "sourceColumn": "FirstName",
            "sourceProviderType": "nvarchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70697492-d808-4324-9cb5-f5a71ed1b003",
            "sourceColumn": "LastName",
            "sourceProviderType": "nvarchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "BirthDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "b38d23a1-2a38-48a8-814e-87339f119c47",
            "sourceColumn": "BirthDate",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "MaritalStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9402d10-55e0-4c42-9b15-55b278355ccf",
            "sourceColumn": "MaritalStatus",
            "sourceProviderType": "nchar",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5fc50e8-bfa7-409d-8d50-556058d466cc",
            "sourceColumn": "Gender",
            "sourceProviderType": "nvarchar(1)",
            "summarizeBy": "none"
          },
          {
            "name": "EmailAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a57693c2-c974-4ead-9520-5b88672ebca0",
            "sourceColumn": "EmailAddress",
            "sourceProviderType": "nvarchar(50)",
            "summarizeBy": "none"
          },
          {
            "name": "YearlyIncome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0076b2ce-69c6-4f33-a875-8252964c0662",
            "sourceColumn": "YearlyIncome",
            "sourceProviderType": "money",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalChildren",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5ceb37f5-6b16-49d3-9b28-8cee75fc6860",
            "sourceColumn": "TotalChildren",
            "sourceProviderType": "tinyint",
            "summarizeBy": "sum"
          },
          {
            "name": "EnglishEducation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afd7dc8b-5764-4903-9186-c45fd6a6eef3",
            "sourceColumn": "EnglishEducation",
            "sourceProviderType": "nvarchar(40)",
            "summarizeBy": "none"
          },
          {
            "name": "EnglishOccupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b261e464-f6f0-4aac-afb3-dece7cdd67a3",
            "sourceColumn": "EnglishOccupation",
            "sourceProviderType": "nvarchar(100)",
            "summarizeBy": "none"
          },
          {
            "name": "HouseOwnerFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55e3061d-3e8f-4bc0-9d8e-ab8c4e6df1f4",
            "sourceColumn": "HouseOwnerFlag",
            "sourceProviderType": "nchar",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "329a9d01-94a4-436a-ac9a-5a8bf2537678",
        "partitions": [
          {
            "name": "Customer Lookup DQ",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"AdventureWorksDW2019\", [Query=\"SELECT TOP (100) [CustomerKey]#(lf)      ,[GeographyKey]#(lf)      ,[CustomerAlternateKey]#(lf)      ,[Title]#(lf)      ,[FirstName]#(lf)      ,[LastName]#(lf)      ,[BirthDate]#(lf)      ,[MaritalStatus]#(lf)      ,[Gender]#(lf)      ,[EmailAddress]#(lf)      ,[YearlyIncome]#(lf)      ,[TotalChildren]#(lf)      ,[EnglishEducation]#(lf)      ,[EnglishOccupation]#(lf)      ,[HouseOwnerFlag]#(lf)  FROM [AdventureWorksDW2019].[dbo].[DimCustomer]\", CreateNavigationProperties=false])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c5f36122-e0bb-46cf-b521-32a4ba86d05d",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "count"
          },
          {
            "name": "GeographyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b978efdb-8f95-4fa3-80a7-174ba7b2df96",
            "sourceColumn": "GeographyKey",
            "summarizeBy": "count"
          },
          {
            "name": "CustomerAlternateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83359f8c-6e22-49d3-9d2b-ee65d9414299",
            "sourceColumn": "CustomerAlternateKey",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "634af670-2a00-42f6-a80f-9a641269a900",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0372fbe5-eafc-4354-97d4-ccf23f945648",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c8288d0-1474-4998-80be-130ce4887c84",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          },
          {
            "name": "BirthDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "1be609a1-03e8-44b2-b4d0-62bf0cfbf0a9",
            "sourceColumn": "BirthDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3acdb546-8f22-4f5e-9346-fb0821380efb"
                },
                "isDefault": true,
                "relationship": "4a1502c3-bc15-498d-8955-ba41c3c58fdd"
              }
            ]
          },
          {
            "name": "MaritalStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc575aec-588c-4c26-90fa-f85454c93bda",
            "sourceColumn": "MaritalStatus",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84cf886b-d0fe-412f-bf37-b5b4daf8b701",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "EmailAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4919a6b2-6e49-4989-a4e8-23a94ca2796a",
            "sourceColumn": "EmailAddress",
            "summarizeBy": "none"
          },
          {
            "name": "YearlyIncome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8271980c-828b-4b1f-bc02-100f43da646c",
            "sourceColumn": "YearlyIncome",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalChildren",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "76208505-b46e-4752-b686-ffb80d0fb00a",
            "sourceColumn": "TotalChildren",
            "summarizeBy": "sum"
          },
          {
            "name": "EnglishEducation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0328e5d-a68e-4282-8308-127318810b85",
            "sourceColumn": "EnglishEducation",
            "summarizeBy": "none"
          },
          {
            "name": "EnglishOccupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c16f2eca-7cfc-41db-8aec-0f59f2d6166f",
            "sourceColumn": "EnglishOccupation",
            "summarizeBy": "none"
          },
          {
            "name": "HouseOwnerFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81249cf3-4c3a-4f45-a1da-5f27a11c6a1e",
            "sourceColumn": "HouseOwnerFlag",
            "summarizeBy": "none"
          },
          {
            "name": "Domain",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a90d3680-ad37-4dfc-883e-523552d36a10",
            "sourceColumn": "Domain",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fc0ce0bf-f023-406c-9873-d22cef86f976",
        "partitions": [
          {
            "name": "Customer Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"AdventureWorksDW2019\", [Query=\"SELECT TOP (100) [CustomerKey]#(lf)      ,[GeographyKey]#(lf)      ,[CustomerAlternateKey]#(lf)      ,[Title]#(lf)      ,[FirstName]#(lf)      ,[LastName]#(lf)      ,[BirthDate]#(lf)      ,[MaritalStatus]#(lf)      ,[Gender]#(lf)      ,[EmailAddress]#(lf)      ,[YearlyIncome]#(lf)      ,[TotalChildren]#(lf)      ,[EnglishEducation]#(lf)      ,[EnglishOccupation]#(lf)      ,[HouseOwnerFlag]#(lf)  FROM [AdventureWorksDW2019].[dbo].[DimCustomer]\", CreateNavigationProperties=false]),",
                "    #\"Inserted Text After Delimiter\" = Table.AddColumn(Source, \"Domain\", each Text.AfterDelimiter([EmailAddress], \"@\"), type text),",
                "    #\"Extracted Text Before Delimiter\" = Table.TransformColumns(#\"Inserted Text After Delimiter\", {{\"Domain\", each Text.BeforeDelimiter(_, \".com\", {0, RelativePosition.FromEnd}), type text}}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Extracted Text Before Delimiter\",{{\"Domain\", Text.Proper, type text}}),",
                "    #\"Replace Value\" = Table.ReplaceValue(#\"Capitalized Each Word\",\"-\",\" \",Replacer.ReplaceText,{\"Domain\"})",
                "in",
                "    #\"Replace Value\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_3acdb546-8f22-4f5e-9346-fb0821380efb",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f4b38a7f-96ac-4e60-97ab-377a0e306fcc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cee903c4-77db-4c95-b7b0-d87285b822d6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d3284c28-c243-429a-847a-1e94d4736650",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "694e4ef0-f49d-41c5-bd6d-7d85b0b0f37b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cad07def-3c21-4ebd-9695-bb09d0fa759c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "85dd8839-3ad9-400b-97d7-e02360be87e3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "43539751-d247-4dd8-82df-e214ddc41cb7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5a6a34b2-d4c8-4ade-ad0b-4ee38246ede0",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "041f3579-a2f7-4ec4-b343-b9c2d2b9b003",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5cc5c179-cd76-41a7-9224-aa1e3a49e427",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2bc27746-0e23-4793-baf7-dd89dc61a1c0",
                "ordinal": 3
              }
            ],
            "lineageTag": "964a8223-dc5f-49b1-8df3-8e3acff65502"
          }
        ],
        "isHidden": true,
        "lineageTag": "a5c9be83-b626-4314-97e6-da319b62b87f",
        "partitions": [
          {
            "name": "LocalDateTable_3acdb546-8f22-4f5e-9346-fb0821380efb",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Customer Lookup'[BirthDate])), 1, 1), Date(Year(MAX('Customer Lookup'[BirthDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}